site_name: "JDG — ИП в Польше"
site_url: https://sobolevbel.githun.io
theme:
  name: readthedocs

nav:
  - Главная: index.md
  - PESEL: pesel.md
  - Profil Zaufany: pz.md
  - Регистрация: registration.md
  - ZUS: zus.md
  - Налоги: taxes.md
  - Декларации: declarations.md
  - Легализация: legalization.md
