name: JDG CI 

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: mkdocs build --verbose
      - if: github.ref == 'refs/heads/master'
        run: mkdocs gh-deploy --force
